### ISSUE TITLE
Possibly incorrect usage of `sync.WaitGroup` in the example

### ISSUE THREAD

**Issue by domust** [esiqveland/notify#15]
Hi, great library.

One thing I've noticed while using it is that `sync.WaitGroup` in the examples is not really needed, because the library uses it under the hood: https://github.com/esiqveland/notify/blob/master/notification.go#L274

**Comment by domust** [comment]
My mistake, it is actually needed for the event handlers to work when clicking the notification.
Another case I'm confused by is that `wg.Done()` method was only called in `onAction` event handler in the examples, but not in `onClosed`. Wouldn't in block until the notification is explicitly clicked on? What about when it times out? I've tried adding `wg.Done()` to both event handlers in my own code and while it worked most of the time.. sometimes it would cause:
```
panic: sync: negative WaitGroup counter
```

**Comment by esiqveland** [comment]
The usage of waitgroup in the examples is only to keep the program open and running so you can see the different notification responses/data flow back to the process. We wait in the action handler because that is the handler least likely to be invoked, as it requires the user actually click on one of the buttons in the notification UI. You can do whatever you want in your own programs, but Id like the example to display how the responses come back. The sync group inside the library is to make sure we exit cleanly and only once.

**Comment by domust** [comment]
Thanks for the clarification! I've tested to see what actually happens if the `ExpiryTimeout` is set. Only `onClose` handler is invoked if the user did not click anything. If they did, only `onAction` is invoked so it should be safe to have `wg.Done()` in both of them.

**Comment by esiqveland** [comment]
Ok, I might change it do `wg.Done()` in both then. I remember that some of these things were up to the notification server. F.ex. gnome-shell had a tendency to send the CloseNotifcation signal twice in earlier versions.

**Comment by esiqveland** [comment]
> I've tried adding `wg.Done()` to both event handlers in my own code and while it worked most of the time.. sometimes it would cause:
> 
> ```
> panic: sync: negative WaitGroup counter
> ```

Yes, this is the reason it only does so in action invoked. The important thing in the example is just to leave the process running so we can see the signals coming back without exiting.
