### ISSUE TITLE
Possible issue with v0.13 example

### ISSUE THREAD

**Issue by lordofscripts** [esiqveland/notify#22]
When I was working in my wrapper (your package **v0.11**) I noticed you called `wg.Done()` within the `onAction` handler but not in `onClose`.

In your new update (**v0.13.2**) you call `wg.Done()` in both handlers. I think there is an issue there because at least on the notification server I use `(Dunst)`, you can receive first `onAction` followed by `onClose` resulting in `wg.Done()` being called twice for the same notification.

**Comment by esiqveland** [comment]
Yes I did that on purpose to make the example blow up when the notification server sends duplicates. This still happens quite a bit on GNOME. The `sync.WaitGroup` is only in the example, so the example does not exit after sending the notification, as I am trying to demonstrate the `onAction` callback. I dont expect anyone in a real application need to wait for the handler in such a way. Since dbus is also a bus, it means you get any action signal, also from other clients that are sending notifications.
